### ISSUE TITLE
Error Building RepeatMasker.lib with Dfam3.7 and RBRM: TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by TobyBaril** [Dfam-consortium/FamDB#4]
I am configuring RepeatMasker with Dfam 3.7 and RepBase RepeatMasker edition. When building the fasta version of the library in the final step of the configuration, I get the following error:

```
Traceback (most recent call last):
  File "/data/toby/tools/earlGrey/RepeatMasker/famdb.py", line 1914, in <module>
    main()
  File "/data/toby/tools/earlGrey/RepeatMasker/famdb.py", line 1907, in main
    args.func(args)
  File "/data/toby/tools/earlGrey/RepeatMasker/famdb.py", line 1692, in command_families
    print_families(args, families, True, target_id)
  File "/data/toby/tools/earlGrey/RepeatMasker/famdb.py", line 1634, in print_families
    buffer=buffer_spec
  File "/data/toby/tools/earlGrey/RepeatMasker/famdb.py", line 402, in to_fasta
    for clade_id in self.clades:
TypeError: 'NoneType' object is not iterable
```

The RepeatMasker.lib file is also only 8Mb at the end of this so does not contain all the sequences.

**Comment by asgray** [comment]
Hi Toby, this response is overdue, but I thought I'd check. Since Dfam and FamDB have both been updated, is this still an issue?
